### PR TITLE
Don't retain PhoneNumberActivity in Recents

### PR DESCRIPTION
**Pull request by jaydeep17**
Possible fix for issue #5  and issue #10 
Also mentioned in the forum [here](https://twittercommunity.com/t/android-digits-creates-a-separate-window/49316).

### CODE REVIEW

**Comment by atrepeklis** [comment]
Wouldn't this approach though create the following issue: User swaps to messaging app to check the code and then can't find the PhoneNumberActivity to enter the code back and continue the login process?

**Comment by jaydeep17** [comment]
Is there any other workaround you know of, because I don't know any other way to handle it.
Instead of this(pull request) approach we could clear the activity after the authentication is done, but I'm not sure if android provides a way to do that.

**Comment by atrepeklis** [comment]
What I have done for now and seems to be working for API 21 and above is the following, which actually searches for the task named "PhoneNumberActivity" and then kill it. I call this after the success callback method of Digits:

    ActivityManager am = (ActivityManager) getSystemService(ACTIVITY_SERVICE);
    if (Build.VERSION.SDK_INT >= 21){
        List<ActivityManager.AppTask> tasks = am.getAppTasks();
        for (ActivityManager.AppTask task : tasks){
            if (task.getTaskInfo().baseIntent.getComponent()
            .getClassName().contains("PhoneNumberActivity")) {
                task.finishAndRemoveTask();
            }
        }
    }

**Comment by efrohnhoefer** [comment]
As previously mentioned the user will be unable to switch between messaging app and Digits. The team will address this issue in our next release.

**Pull request closed without merging**
